dist: trusty
sudo: required
language: c
cache:
  apt: true
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  # Main test targets
  matrix:
  - TEST_TARGET="8.5.dev"
  - TEST_TARGET="8.6.dev"
  - TEST_TARGET="8.7.dev"
  - TEST_TARGET="dev"

# matrix:
#  allow_failures:
  # 8.5.dev is too slow to build mathcomp
  # - env: TEST_TARGET="8.5.dev"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config var root
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
- opam pin add -y -n coq -k version ${TEST_TARGET}
- opam install -y -v -j ${NJOBS} coq ${EXTRA_OPAM}
- opam list

script:
- echo 'Building Mathcomp...' && echo -en 'travis_fold:start:mathcomp.build\\r'
- export PATH=`pwd`/coq-${TEST_TARGET}/bin:$PATH
- cd mathcomp
# We lack a few minutes to be able to build the whole theorem.
- sed -i.bak '/stripped_odd_order_theorem/d' Make
- sed -i.bak '/PFsection6\.v/d'              Make
- sed -i.bak '/PFsection7\.v/d'              Make
- sed -i.bak '/PFsection8\.v/d'              Make
- sed -i.bak '/PFsection9\.v/d'              Make
- sed -i.bak '/PFsection1.\.v/d'             Make
- "if [ ${TEST_TARGET} = \"v8.5\" ]; then sed -i.bak '/primproj\\.v/d' Make ; sed -i.bak '/odd_order/d' Make ; fi"
- make Makefile.coq
- make -f Makefile.coq -j ${NJOBS} all
- echo -en 'travis_fold:end:mathcomp.build\\r'
