Require Export mathcomp.algebra.all.
Require Export mathcomp.attic.all.
Require Export mathcomp.character.all.
Require Export mathcomp.discrete.all.
Require Export mathcomp.field.all.
Require Export mathcomp.fingroup.all.
Require Export mathcomp.odd_order.all.
Require Export mathcomp.real_closed.all.
Require Export mathcomp.solvable.all.
Require Export mathcomp.ssreflect.all.
