## File initially generated by createOverlay
## and then supposedly modified manually.
## Some hints for manual modifications are in the file,
## but the full doc is on nixos / nix packages website:
## https://nixos.org/manual/nixpkgs/stable/#sec-language-coq

{
  lib,
  coq,
  mkCoqDerivation,
  mathcomp,
  multinomials,
  mathcomp-classical,
  stdlib,
  ## declare extra dependencies here, to be used in propagateBuildInputs e.g.
  # , mathcomp, coq-elpi
  version ? null,
}:

let
  derivation = mkCoqDerivation {
    pname = "fpseries";
    repo = "fpseries";
    owner = "hivert";

    inherit version;
## The `defaultVersion` attribute is important for nixpkgs but can be kept unchanged
## for local usage since it will be ignored locally if
## - this derivation corresponds to the main attribute,
## - or its version is overridden (by a branch, PR, url or path) in `.nix/config.nix`.
    defaultVersion =
      let
        case = coq: mc: out: {
          cases = [
            coq
            mc
          ];
          inherit out;
        };
      in
      with lib.versions;
      lib.switch
        [ coq.version mathcomp.version ]
        [
          (case (range "9.0" "9.1") (isGe "2.5.0") "2.0.3")
        ]
        null;

  ## Declare existing releases
  ## leave sha256 empty at first and then copy paste
  ## the resulting sha given by the error message
  # release."1.1.1".sha256 = "";
  ## if the tag is not exactly the version number you can amend like this
  # release."1.1.1".rev = "v1.1.1";
  ## if a consistent scheme gives the tag from the release number, you can do like this:
    release = {
      "2.0.3".hash = "";
    };
    releaseRev = v: "v${v}";

  ## Add dependencies in here. In particular you can add
  ## - arbitrary nix packages (you need to require them at the beginning of the file)
  ## - Coq packages (require them at the beginning of the file)
  ## - OCaml packages (use `coq.ocamlPackages.xxx`, no need to require them at the beginning of the file)
    propagatedBuildInputs = [
      mathcomp-classical
      multinomials
      stdlib
    ];

  ## Does the package contain OCaml code?
  # mlPlugin = false;

  ## Give some meta data
  ## This is needed for submitting the package to nixpkgs but not required for local use.
    meta = {
      description = "Formal Power Series";
      license = lib.licenses.gpl3Only;
    };
    ## Describe your package in one sentence
    # description = "";
    ## Kindly ask one of these people if they want to be an official maintainer.
    ## (You might also consider adding yourself to the list of maintainers)
    # maintainers = with maintainers; [ cohencyril siraben vbgl Zimmi48 ];
    ## Pick a license from
    ## https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix
    # license = licenses.mit;
  };
in
derivation
