#!/bin/bash

set -e
set -x

for pkg in ssreflect fingroup algebra field solvable character real_closed odd_order
do
pkgdir="$(git root)/opam/extra-dev/packages/coq-mathcomp-$pkg/coq-mathcomp-$pkg.dev"
mkdir -p $pkgdir
cp $(git root)/mathcomp/$pkg/opam $pkgdir/opam
cp $(git root)/mathcomp/$pkg/descr $pkgdir/descr
sed -r "/^(build|install)/s?make?make \"-C\" \"mathcomp/$pkg\"?" -i $pkgdir/opam
echo "git: \"https://github.com/math-comp/math-comp.git\"" > $pkgdir/url
done

for pkg in ssreflect fingroup algebra field solvable character odd_order
do
pkgdir="$(git root)/opam/released/packages/coq-mathcomp-$pkg/coq-mathcomp-$pkg.1.6"
mkdir -p $pkgdir
cp $(git root)/mathcomp/$pkg/opam $pkgdir/opam
cp $(git root)/mathcomp/$pkg/descr $pkgdir/descr
sed -r "/^version/s?dev?1.6?" -i $pkgdir/opam
sed -r "/^depends.*coq-mathcomp.*/s?dev?1.6?" -i $pkgdir/opam
sed -r "/^(build|install)/s?make?make \"-C\" \"mathcomp/$pkg\"?" -i $pkgdir/opam
echo "http: \"http://github.com/math-comp/math-comp/archive/mathcomp-1.6.tar.gz\"" > $pkgdir/url
echo "checksum: \"038ba80c0d6b430428726ae4d00affcf\"" >> $pkgdir/url

done
