#!/bin/bash

args="$@"
echo "calling coqdep on $args" 1>&2

mkdir bkpcoqdep

while [[ $# > 0 ]]
do
key="$1"

case $key in
    *.v)
	mkdir -p $(dirname bkpcoqdep/$key)
        cp $key bkpcoqdep/$key
	sed "s/^From.*//" -i $key
    ;;
    *)
    ;;
esac
shift
done

COQBIN="$(dirname $(which coqtop))/"
$COQBIN/coqdep $args

for f in $(find bkpcoqdep -name "*.v")
do
mv $f ${f##bkpcoqdep/}
done

rm -rf bkpcoqdep
