# -*- Makefile -*-

COQPROJECT="Make"

# --------------------------------------------------------------------
include ../Makefile.common

# --------------------------------------------------------------------
COQMAKEOPTIONS=--no-print-directory

