define coqmakefile
	(echo "Generating Makefile.coq for Coq $(V) with COQBIN=$(COQBIN)";\
	ln -sf $(1)/plugin/$(V)/ssreflect.mllib .;\
	ln -sf $(1)/plugin/$(V)/ssrmatching.mli .;\
	ln -sf $(1)/plugin/$(V)/ssrmatching.ml4 .;\
	ln -sf $(1)/plugin/$(V)/ssrcommon.mli .;\
	ln -sf $(1)/plugin/$(V)/ssrcommon.ml4 .;\
	ln -sf $(1)/plugin/$(V)/ssreflect.ml4 .;\
	$(COQBIN)coq_makefile -f Make -o Makefile.coq)
endef

