BRANCH_coq = $(shell $(COQBIN)coqtop -v | head -1 \
	     | sed 's/.*version \([0-9]\.[0-9]\)[^ ]* .*/v\1/')

HASH_coq = $(shell echo Quit. | $(COQBIN)coqtop 2>&1 | head -1 \
	   | sed 's/^.*(\([a-f0-9]*\)).*/\1/' )

HASH_coq_v85beta1 = eaa3d0b15adf4eb11ffb00ab087746a5b15c4d5d
HASH_coq_v85beta2 = 94afd8996251c30d2188a75934487009538e1303

V=$(BRANCH_coq)
ifeq "$(HASH_coq)" "$(HASH_coq_v85beta1)"
V=v8.5beta1
endif
ifeq "$(HASH_coq)" "$(HASH_coq_v85beta2)"
V=v8.5beta2
endif
